services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-18}-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USERNAME:-test}
      POSTGRES_PASSWORD: ${PASSWORD:-test}
      POSTGRES_DB: ${DBNAME:-test}
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $USERNAME"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:${MYSQL_VERSION:-9}
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: ${PASSWORD:-test}
        MYSQL_USER: ${USERNAME:-test}
        MYSQL_PASSWORD: ${PASSWORD:-test}
        MYSQL_DATABASE: ${DBNAME:-test}
    ports:
        - "${MYSQL_PORT:-13306}:3306"
    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 30s

